applisun_aire_jeux:
    resource: "@ApplisunAireJeuxBundle/Controller/"
    type:     annotation
    prefix:   /
    
user_bundle:
   resource: "@ApplisunAireJeuxBundle/Resources/config/routing.yml"
   
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

