security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
           id: fos_user.user_provider.username

    firewalls:
        wsse_secured:
            pattern:   ^/api/(aires|comments|votes)
            wsse:      true
            stateless:    true   
        main:
           pattern: ^/
           form_login:
               check_path: /login_check
               login_path: /login
               provider: fos_userbundle
           logout:
               path:    /logout
               target: /
              # provider: fos_userbundle
              # csrf_provider: form.csrf_provider

           anonymous:    true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
    access_control:
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/aire/new, role: ROLE_USER }
       - { path: ^/aire/edit, role: ROLE_USER }
       - { path: ^/admin/, role: ROLE_ADMIN }
