<?php

namespace Applisun\AireJeuxBundle\Entity;

/**
 * AireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AireRepository extends \Doctrine\ORM\EntityRepository
{
}
