<?php

namespace Applisun\AireJeuxBundle\Repository;

use Symfony\Component\DependencyInjection\ContainerInterface;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AireRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getAireByVille(ContainerInterface $container, $villeId, $page)
    {
        $maxperpage = $container->getParameter('maxperpage');
        
        $query = $this->getEntityManager()
		              ->createQuery('SELECT a FROM ApplisunAireJeuxBundle:Aire a WHERE a.ville = :id')
		              ->setParameter('id', $villeId)
                              ->setFirstResult(($page-1) * $maxperpage)
                              ->setMaxResults($maxperpage);
 
        return new Paginator($query);
    }
    
    public function getCountAireByVille($villeId)
    {
        $query = $this->getEntityManager()
		              ->createQuery('SELECT a FROM ApplisunAireJeuxBundle:Aire a WHERE a.ville = :id')
		              ->setParameter('id', $villeId);
        
        return count($query->getResult());
    }
    
    public function getAllAireByVille($villeId)
    {
        return $this->getEntityManager()
		              ->createQuery('SELECT a FROM ApplisunAireJeuxBundle:Aire a WHERE a.ville = :id')
		              ->setParameter('id', $villeId)->getResult();
    }
}
