<?php

namespace Applisun\AireJeuxBundle\Repository;

use Symfony\Component\DependencyInjection\ContainerInterface;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * DepartementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllAires(){
        $qb = $this->createQueryBuilder('d');
        $qb->select('d','count(a.id) as nbr');
        $qb->join('d.villes', 'v');
        $qb->leftJoin('v.aires', 'a');
        $qb->groupBy('d.id');
        $qb->orderBy('nbr', 'DESC');
        $results = $qb->getQuery()->getResult();
        $aires = array();
        foreach ($results as $result){
            $aires[] = array('value'=> $result['nbr'], "hc-key" => $result[0]->getHcKey(), "id" => $result[0]->getId(), "slug" => $result[0]->getSlug());
        }                
        
        return $aires;
    }
}

