<?php

namespace Applisun\AireJeuxBundle\Repository;

/**
 * departementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementRepository extends \Doctrine\ORM\EntityRepository
{
}
