parameters:
    applisun_aire_jeux.aire_manager.class: Applisun\AireJeuxBundle\Service\AireManager
    applisun_aire_jeux.comment_manager.class: Applisun\AireJeuxBundle\Service\CommentManager
    applisun_aire_jeux.image_manager.class: Applisun\AireJeuxBundle\Service\ImageManager
    applisun_aire_jeux.form.type.aire.class: Applisun\AireJeuxBundle\Form\Type\AireType
    applisun_aire_jeux.form.image.type.extension.class: Applisun\AireJeuxBundle\Form\Extension\ImageTypeExtension
    applisun_aire_jeux.form.handler.aire.class: Applisun\AireJeuxBundle\Form\Handler\AireFormHandler
    applisun_aire_jeux.voter.user_aire_modify.class: Applisun\AireJeuxBundle\Security\UserAireModifyVoter
    applisun_aire_jeux.form.type.vote_aire.class: Applisun\AireJeuxBundle\Form\Type\VoteType
    applisun_aire_jeux.form.type.comment_aire.class: Applisun\AireJeuxBundle\Form\Type\CommentType
    applisun_aire_jeux.voter.user_aire_vote.class: Applisun\AireJeuxBundle\Security\UserAireVoter
    applisun_aire_jeux.voter.user_aire_comment.class: Applisun\AireJeuxBundle\Security\UserAireCommentVoter
    applisun_aire_jeux.voter.user_comment_modify.class: Applisun\AireJeuxBundle\Security\UserCommentModifyVoter
    applisun_aire_jeux.twigextension.breadcrumb_extension.class: Applisun\AireJeuxBundle\Twig\BreadCrumbExtension
    applisun_aire_jeux.twigextension.googlemaps_extension.class: Applisun\AireJeuxBundle\Twig\GoogleMapsExtension
    applisun_aire_jeux.twigextension.average_extension.class: Applisun\AireJeuxBundle\Twig\DisplayAverageExtension
    applisun_aire_jeux.security.authentication_provider.class: Applisun\AireJeuxBundle\Security\Authentication\Provider\WsseProvider
    applisun_aire_jeux.security.firewall_listener.class: Applisun\AireJeuxBundle\Security\Firewall\WsseListener
    maxperpage: 10
    searchmaxperpage: 24
    maxcommentperpage: 5
    maxuserperpage: 20
    perimeter: 0.05
    limit: 5
    sizeimage:
        normal: 500x280
        thumbnail: 100x56
    
services:
    # Manager
    applisun_aire_jeux.aire_manager:
        class:     %applisun_aire_jeux.aire_manager.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.context"
            
    applisun_aire_jeux.comment_manager:
        class:     %applisun_aire_jeux.comment_manager.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.context"
    
    applisun_aire_jeux.image_manager:
        class:     %applisun_aire_jeux.image_manager.class%
        
    # Form types
    applisun_aire_jeux.form.type.aire:
        class: %applisun_aire_jeux.form.type.aire.class%
        tags:
            - { name: form.type, alias: applisun_aire_form }
            
    applisun_aire_jeux.form.type.vote_aire:
        class: %applisun_aire_jeux.form.type.vote_aire.class%
        tags:
            - { name: form.type, alias: vote_aire }
            
    applisun_aire_jeux.form.type.comment_aire:
        class: %applisun_aire_jeux.form.type.comment_aire.class%
        tags:
            - { name: form.type, alias: comment_aire }
            
            
    #Form Extension
    applisun_aire_jeux.image_type_extension:
        class: %applisun_aire_jeux.form.image.type.extension.class%
        tags:
            - { name: form.type_extension, alias: file }
        
    #Form handler        
    applisun_aire_jeux.form.handler.aire:
        class: %applisun_aire_jeux.form.handler.aire.class%
        arguments: [@doctrine.orm.entity_manager, @applisun_aire_jeux.aire_manager, @applisun_aire_jeux.image_manager, @form.factory]
        
    # Security voter
    applisun_aire_jeux.voter.user_modify_aire:
        class: %applisun_aire_jeux.voter.user_aire_modify.class%
        tags:
            - { name: security.voter }
            
    applisun_aire_jeux.voter.user_aire:
        class: %applisun_aire_jeux.voter.user_aire_vote.class%
        tags:
            - { name: security.voter }
            
    applisun_aire_jeux.voter.user_aire_comment:
        class: %applisun_aire_jeux.voter.user_aire_comment.class%
        tags:
            - { name: security.voter }
            
    applisun_aire_jeux.voter.user_comment_modify:
        class: %applisun_aire_jeux.voter.user_comment_modify.class%
        tags:
            - { name: security.voter }
            
    #Twig Extension
    applisun_aire_jeux.twig.breadcrumb_extension:
        class: %applisun_aire_jeux.twigextension.breadcrumb_extension.class%
        tags:
            - { name: twig.extension }
            
    applisun_aire_jeux.twig.googlemaps_extension:
        class: %applisun_aire_jeux.twigextension.googlemaps_extension.class%
        tags:
            - { name: twig.extension }
            
    applisun_aire_jeux.twig.average_extension:
        class: %applisun_aire_jeux.twigextension.average_extension.class%
        tags:
            - { name: twig.extension }        
            
    #Security
    wsse.security.authentication.provider:
        class:  %applisun_aire_jeux.security.authentication_provider.class%
        arguments: ['', %kernel.cache_dir%/security/nonces]

    wsse.security.authentication.listener:
        class:  %applisun_aire_jeux.security.firewall_listener.class%
        arguments: [@security.context, @security.authentication.manager]
     
    #Utility 
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }    


