parameters:
    applisun_aire_jeux.aire_manager.class: Applisun\AireJeuxBundle\Service\AireManager
    applisun_aire_jeux.form.type.aire.class: Applisun\AireJeuxBundle\Form\Type\AireType
    applisun_aire_jeux.form.image.type.extension.class: Applisun\AireJeuxBundle\Form\Extension\ImageTypeExtension
    applisun_aire_jeux.form.handler.aire.class: Applisun\AireJeuxBundle\Form\Handler\AireFormHandler
    applisun_aire_jeux.voter.user_aire_modify.class: Applisun\AireJeuxBundle\Security\UserAireModifyVoter
    
services:
    # Manager
    applisun_aire_jeux.aire_manager:
        class:     %applisun_aire_jeux.aire_manager.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.context"
    
    # Form types
    applisun_aire_jeux.form.type.media:
        class: %applisun_aire_jeux.form.type.aire.class%
        tags:
            - { name: form.type, alias: applisun_aire_form }
            
    #Form Extension
    applisun_aire_jeux.image_type_extension:
        class: %applisun_aire_jeux.form.image.type.extension.class%
        tags:
            - { name: form.type_extension, alias: file }
        
    #Form handler        
    applisun_aire_jeux.form.handler.aire:
        class: %applisun_aire_jeux.form.handler.aire.class%
        arguments: [@doctrine.orm.entity_manager, @applisun_aire_jeux.aire_manager, @form.factory]
        
    # Security voter
    applisun_aire_jeux.voter.user_media:
        class: %applisun_aire_jeux.voter.user_aire_modify.class%
        tags:
            - { name: security.voter }


